# Site settings
title: Worst Party Ever
email: worstpartyevershow@gmail.com
url: http://www.worstpartyevershow.com
description: "Home of the Worst Party Ever Show"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Time Travel Party

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/WPEShow
  - title: facebook
    url: https://www.facebook.com/WorstPartyEverShow/

# Build settings
markdown: kramdown
permalink: pretty
